In [31]:
import pandas as pd
import numpy as np

df = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv", sep='\t')

In [32]:
# Display the last 7 rows of the DataFrame
df.head(7)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69

In [33]:
# Print a summary of the df including the index dtype and columns dtypes, non-null values, and memory usage.

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   str
dtypes: int64(2), str(3)
memory usage: 180.7 KB

In [34]:
# Determine how many observations have missing item_price in the dataset

int(df['item_price'].isnull().sum())

0

In [35]:
# Print the names of the columns in the df

list(df.columns)

['order_id', 'quantity', 'item_name', 'choice_description', 'item_price']

In [36]:
# Identify which item_name appears most frequently in the orders

df.groupby('item_name').size().sort_values(ascending=False).head(1)

item_name
Chicken Bowl    726
dtype: int64

In [37]:
# Determine how many distinct item_name values are present in the dataset
list(df['item_name'].unique())

['Chips and Fresh Tomato Salsa',
 'Izze',
 'Nantucket Nectar',
 'Chips and Tomatillo-Green Chili Salsa',
 'Chicken Bowl',
 'Side of Chips',
 'Steak Burrito',
 'Steak Soft Tacos',
 'Chips and Guacamole',
 'Chicken Crispy Tacos',
 'Chicken Soft Tacos',
 'Chicken Burrito',
 'Canned Soda',
 'Barbacoa Burrito',
 'Carnitas Burrito',
 'Carnitas Bowl',
 'Bottled Water',
 'Chips and Tomatillo Green Chili Salsa',
 'Barbacoa Bowl',
 'Chips',
 'Chicken Salad Bowl',
 'Steak Bowl',
 'Barbacoa Soft Tacos',
 'Veggie Burrito',
 'Veggie Bowl',
 'Steak Crispy Tacos',
 'Chips and Tomatillo Red Chili Salsa',
 'Barbacoa Crispy Tacos',
 'Veggie Salad Bowl',
 'Chips and Roasted Chili-Corn Salsa',
 'Chips and Roasted Chili Corn Salsa',
 'Carnitas Soft Tacos',
 'Chicken Salad',
 'Canned Soft Drink',
 'Steak Salad Bowl',
 '6 Pack Soft Drink',
 'Chips and Tomatillo-Red Chili Salsa',
 'Bowl',
 'Burrito',
 'Crispy Tacos',
 'Carnitas Crispy Tacos',
 'Steak Salad',
 'Chips and Mild Fresh Tomato Salsa',
 'Veggie Soft Tacos',
 'Carnitas Salad Bowl',
 'Barbacoa Salad Bowl',
 'Salad',
 'Veggie Crispy Tacos',
 'Veggie Salad',
 'Carnitas Salad']

In [38]:
# Create a new df containing only the rows where the item_name is Chicken Bowl

chicken_bowl_df = df[df['item_name'] == 'Chicken Bowl']
chicken_bowl_df.head(5)

,order_id,quantity,item_name,choice_description,item_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$8.75
26,13,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",$8.49

In [39]:
# Convert item_price from string to float and remove the dollar sign
df['item_price'] = df['item_price'].str.replace('$', '').astype(float)
df.head(5)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98

In [43]:
# Calculate the avg item_price across all orders

avg_item_price = df['item_price'].mean()
print(f"The average item price across all orders is: ${avg_item_price:.2f}")

The average item price across all orders is: $7.46

In [47]:
# Determine the total number of unique orders in the dataset based on the order_id column

unique_orders = df['order_id'].unique()
print(f"The total number of unique orders in the dataset is: {len(unique_orders)}")

The total number of unique orders in the dataset is: 1834